version: '3'
services:
  php:
    build: .
    image: apache-server
    container_name: apache
    restart: always
    volumes:
      #- ./www:/var/www/html
      - www-data:/var/www/html
      - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - 80:80
    links:
      - postgress    
    networks:
      - mynetwork

  postgress:
    image: postgres
    container_name: postgres
    volumes:
      - .db:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: scrum
    restart: always
    networks: 
      - mynetwork

volumes: 
  www-data:
    driver: lebokus/bindfs:latest
    driver_opts: 
      sourcePath: "${PWD}/www"
      map: "${UID}/0:@${UID}/@0"

networks: 
  mynetwork:
    driver: bridge
    