version: '3'
services:
  php:
    build: .
    image: apache-server
    container_name: apache
    restart: always
    volumes:
      - ./www:/var/www/html
    ports:
      - 80:80
    links:
      - postgress    
    networks:
      - mynetwork

  postgress:
    image: postgres
    container_name: postgres
    volumes:
      - .db:/var/lib/postgresql
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: scrum
    restart: always
    networks: 
      - mynetwork

networks: 
  mynetwork:
    driver: bridge
    